USE DENUE;

CREATE TABLE IF NOT EXISTS  `UNIDADES_ECONOMICAS` (
    `ID` NUMERIC(10) PRIMARY KEY,
    `CLEE` VARCHAR(75),
    `NOM_ESTAB` VARCHAR(150),
    `RAZ_SOCIAL` VARCHAR(150),
    `CODIGO_ACT` VARCHAR(6),
    `NOMBRE_ACT` VARCHAR(250),
    `PER_OCU` VARCHAR(20),
    `TIPO_VIAL` VARCHAR(25),
    `NOM_VIAL` VARCHAR(100),
    `TIPO_V_E_1` VARCHAR(40),
    `NOM_V_E_1` VARCHAR(100),
    `TIPO_V_E_2` VARCHAR(40),
    `NOM_V_E_2` VARCHAR(100),
    `TIPO_V_E_3` VARCHAR(40),
    `NOM_V_E_3` VARCHAR(100),
    `NUMERO_EXT` NUMERIC(7),
    `LETRA_EXT` text,
    `EDIFICIO` text,
    `EDIFICIO_E` text,
    `NUMERO_INT` text,
    `LETRA_INT` text,
    `TIPO_ASENT` text,
    `NOMB_ASENT` text,
    `TIPOCENCOM` text,
    `NOM_CENCOM` text,
    `NUM_LOCAL` text,
    `COD_POSTAL` text,
    `CVE_ENT` text,
    `ENTIDAD` text,
    `CVE_MUN` text,
    `MUNICIPIO` text,
    `CVE_LOC` text,
    `LOCALIDAD` text,
    `AGEB` text,
    `MANZANA` text,
    `TELEFONO` text,
    `CORREOELEC` text,
    `WWW` text,
    `TIPOUNIECO` text,
    `LATITUD` text,
    `LONGITUD` text,
    `FECHA_ALTA` DATE,
    `SOURCE_FILE` text,
    `DATE_FILE` text,
    `CATEGORIA` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
;

CREATE TABLE IF NOT EXISTS  UNIDADES_ECONOMICAS_RAW (
    `ID` TEXT, `CLEE` TEXT, `NOM_ESTAB` TEXT, `RAZ_SOCIAL` TEXT, `CODIGO_ACT` TEXT, `NOMBRE_ACT` TEXT, `PER_OCU` TEXT, `TIPO_VIAL` TEXT, `NOM_VIAL` TEXT, `TIPO_V_E_1` TEXT, `NOM_V_E_1` TEXT, `TIPO_V_E_2` TEXT, `NOM_V_E_2` TEXT, `TIPO_V_E_3` TEXT, `NOM_V_E_3` TEXT, `NUMERO_EXT` TEXT, `LETRA_EXT` text, `EDIFICIO` text, `EDIFICIO_E` text, `NUMERO_INT` text, `LETRA_INT` text, `TIPO_ASENT` text, `NOMB_ASENT` text, `TIPOCENCOM` text, `NOM_CENCOM` text, `NUM_LOCAL` text, `COD_POSTAL` text, `CVE_ENT` text, `ENTIDAD` text, `CVE_MUN` text, `MUNICIPIO` text, `CVE_LOC` text, `LOCALIDAD` text, `AGEB` text, `MANZANA` text, `TELEFONO` text, `CORREOELEC` text, `WWW` text, `TIPOUNIECO` text, `LATITUD` text, `LONGITUD` text, `FECHA_ALTA` text, `SOURCE_FILE` text, `DATE_FILE` text, `CATEGORIA` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS UNIDADES_ECONOMICAS_PREPREOCESS AS
SELECT * FROM UNIDADES_ECONOMICAS_RAW LIMIT 0;